project:
  group: laplacian
  name: project.base-template
  type: template
  namespace: laplacian
  version: '1.0.0'
  description: |
    This template generates scripts and other basic files needed for a Laplacian based project.
  source_repository:
    url: https://github.com/nabla-squared/laplacian.project.base-template.git
    branch: master
  subprojects: []
  schemas: []
  plugins: []
  templates:
  - group: laplacian
    name: project.base-template
    version: '1.0.0'
  models:
  - group: laplacian
    name: project-doc.content
    version: '1.0.0'
  model_files: []
  template_files: []
