project:
  group: laplacian
  name: template.project.base
  type: template
  namespace: laplacian
  version: '1.0.0'
  description: |
    This template generates scripts and other files needed for all Laplacian module projects.
  source_repository:
    url: https://github.com/nabla-squared/laplacian.template.project.base.git
    branch: master
  subprojects: []
  schemas: []
  templates: []
  models: []
  model_files: []
  template_files: []
