project:
  sources:
  - "model/project/sources.yaml"
  - "model/project.yaml"
  - "src/.editorconfig.hbs"
  - "src/.gitattributes.hbs"
  - "src/.gitignore.hbs"
  - "src/{if project.document}README.md.hbs"
  - "src/scripts/{each project.subprojects as subproject}{hyphen subproject.group}-{hyphen subproject.name}/publish-local.sh.hbs"
  - "src/scripts/{each project.subprojects as subproject}{hyphen subproject.group}-{hyphen subproject.name}/update-project.sh.hbs"
  - "src/scripts/generate.sh.hbs"
  - "src/scripts/{if project.subprojects}git-status-subprojects.sh.hbs"
  - "src/scripts/{if project.subprojects}update-subprojects.sh.hbs"
  - "src/scripts/laplacian-generate.sh"
  - "src/scripts/{unless (eq project.role 'generator')}publish-local.sh.hbs"
  - "src/scripts/update-project.sh"
