project:
  sources:
  - "src/README.md.hbs"
  - "src/scripts/publish-local.sh.hbs"
  - "src/scripts/update-project.sh"
  - "src/scripts/{each project.subprojects as subproject}{hyphen subproject.group}-{hyphen subproject.name}/update-project.sh.hbs"
  - "src/scripts/{each project.subprojects as subproject}{hyphen subproject.group}-{hyphen subproject.name}/publish-local.sh.hbs"
  - "src/scripts/{if project.subprojects}update-subprojects.sh.hbs"
  - "src/scripts/{if (or project.templates project.template_files)}generate.sh.hbs"
  - "src/scripts/laplacian-generate.sh"
  - "src/scripts/{if project.subprojects}git-status-subprojects.sh.hbs"
  - "src/.gitignore.hbs"
  - "src/.gitattributes.hbs"
  - "src/.editorconfig.hbs"
  - ".editorconfig"
  - ".gitignore"
  - "README.md"
  - ".gitattributes"
  - "model/project.yaml"
  - "model/project/sources.yaml"
